### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by threescales** [WuliHole/hole#10]
![image](https://user-images.githubusercontent.com/15061441/29072498-861f170e-7c7a-11e7-8075-a8a6683a6d8c.png)

**Comment by baoziv587** [comment]
Thanks for your feedback.
Maybe you should only run yarn dev:client and to use [this project](https://github.com/WuliHole/hole-backend) instead of the backend in hole-fe.

### Follow these steps to run the backend server:

* Install PostgresQL(required)
* Install node packages
* exec yarn task:build-schema(NODE_ENV should be `development`  or `test`)

### demo user
`account:1000@qq.com   password:baoziv587`

**Comment by baoziv587** [comment]
由于在webpack-dev-server 用了http代理 后端server起来后 需要访问一次3000端口拿到csrfToken。然后在访问localhost:8080.

**Comment by baoziv587** [comment]
[发现了个新BUG](https://github.com/WuliHole/hole/issues/11)

**Comment by threescales** [comment]
thx,I try one try.
